config_id: 0
optimizer: 're'
search_space: 'nasbench201'
dataset: 'cifar10'
seed: 300
output_path_root: "results"
n_runs: 5
convert_output_only_mode: False

rs:
  budgets: [199]
  n_models_per_budget: 999999
  runtime_limit: 300

dehb:
  min_budget: 1
  max_budget: 199
  brackets: 4
  wallclock: 300
  fevals: 300
  n_workers: 1
  name: dehb

re:
  datasets: [ 'cifar10', 'cifar100', 'imagenet' ]
  predictors: [ 'mlp', 'none' ]
  seeds: [ 0, 1, 2 ]

bananas:
  datasets: [ 'cifar10', 'cifar100', 'imagenet' ]
  predictors: [ 'gp', 'mlp' ]
  seeds: [ 0, 1, 2 ]

smac:
  smac_specific_config_should_go_here: None

nasbench201:
  op_names: ["Identity", "Zero", "ReLUConvBN3x3", "ReLUConvBN1x1", "AvgPool3x3"]
  params: ['op_0', 'op_1', 'op_2', 'op_3', 'op_4', 'op_5']
  optimal_results:
    - cifar10_val_acc: 91.61
    - cifar10_test_acc: 94.37,
    - cifar100_val_acc: 73.49
    - cifar100_test_acc: 73.51,
    - imgnet_val_acc: 46.77
    - imgnet_test_acc: 47.31
